import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {MapPin,Briefcase,House,Music,GraduationCap,LogOut,Save,Heart,Zap,Coins,Shield,ChevronRight,Navigation,Users,ShoppingBag,Wallet,Store, Megaphone, Car, Utensils, Building2, Plus, ArrowUpRight} from 'lucide-react';
import './styles.css';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=SUPABASE_URL&&SUPABASE_KEY?createClient(SUPABASE_URL,SUPABASE_KEY):null;

const places=[
{id:'maitama',name:'Maitama',x:47,y:25,type:'district',desc:'Upscale homes, embassies and premium city life.'},
{id:'wuse',name:'Wuse',x:67,y:40,type:'district',desc:'Markets, shops, food and everyday city energy.'},
{id:'asokoro',name:'Asokoro',x:31,y:44,type:'district',desc:'Premium residences and government quarter.'},
{id:'garki',name:'Garki',x:45,y:67,type:'district',desc:'Business, offices and everyday work life.'},
{id:'jabi',name:'Jabi',x:75,y:70,type:'district',desc:'Mall, lake, nightlife and hangouts.'},
{id:'home',name:'Your House',x:20,y:78,type:'home',desc:'Rest, customize and manage your life.'},
{id:'work',name:'Work Hub',x:57,y:82,type:'work',desc:'Build your career and earn Game Naira.'},
{id:'campus',name:'Abuja Campus',x:83,y:25,type:'school',desc:'Classes, friends, skills and reputation.'},
{id:'citylights',name:'City Lights Club',x:88,y:58,type:'club',desc:'Dance, meet people and raise your social level.'},
{id:'skyline',name:'Skyline Lounge',x:63,y:55,type:'club',desc:'Music, food and late-night social life.'},
{id:'market',name:'Naija Market',x:78,y:49,type:'shop',desc:'Buy clothes, food and lifestyle items.'}
];
const npcs=[['Amaka','47','31'],['Tunde','72','48'],['Zainab','38','60'],['Chinedu','81','66'],['Musa','55','22'],['Dami','28','34']];
const icons={home:House,work:Briefcase,club:Music,school:GraduationCap,district:MapPin,shop:ShoppingBag};
const packs=[{real:1000,game:10000},{real:2000,game:20000},{real:5000,game:50000},{real:10000,game:100000}];
const adSlots=[{id:'billboard-1',name:'Airport Road Billboard',price:50000},{id:'billboard-2',name:'Wuse City Billboard',price:50000},{id:'billboard-3',name:'Jabi Lake Billboard',price:50000},{id:'stats-1',name:'Live City Stats',price:100000}];

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadProfile(session.user.id)},[session]);
 async function loadProfile(uid){const {data,error}=await supabase.from('player_profiles').select('*').eq('id',uid).maybeSingle();if(error){setMsg(error.message);return}if(!data)setMsg('Create your character to enter Abuja.');else setProfile(data)}
 async function auth(e){e.preventDefault();setBusy(true);setMsg('');if(!supabase){setMsg('Add your Supabase keys from .env.example first.');setBusy(false);return}const r=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{display_name:name}}});if(r.error)setMsg(r.error.message);else if(authMode==='signup'&&!r.data.session)setMsg('Check your email to confirm your account, then log in.');setBusy(false)}
 if(!session)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} submit={auth} busy={busy} msg={msg}/>;
 if(!profile)return <CreateCharacter session={session} name={name} setName={setName} onDone={setProfile} msg={msg} setMsg={setMsg}/>;
 return <Game session={session} profile={profile} setProfile={setProfile}/>;
}
function Auth(p){return <main className="auth"><div className="auth-card"><img src="/logo.png" className="logo"/><div className="eyebrow">NIGERIA LIFESTYLE • ABUJA</div><h1>Your Naija. Your Story.</h1><p className="muted">A shared Nigerian life simulator. Work, study, socialize, build a home and make your mark on the city.</p><form onSubmit={p.submit}>{p.mode==='signup'&&<input placeholder="Character name" value={p.name} onChange={e=>p.setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={p.email} onChange={e=>p.setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength="6" value={p.password} onChange={e=>p.setPassword(e.target.value)} required/><button className="primary" disabled={p.busy}>{p.busy?'Please wait…':p.mode==='login'?'Enter the city':'Create account'}</button></form>{p.msg&&<div className="notice">{p.msg}</div>}<button className="link" onClick={()=>p.setMode(p.mode==='login'?'signup':'login')}>{p.mode==='login'?'New here? Create an account':'Already have an account? Log in'}</button></div></main>}
function CreateCharacter({session,name,setName,onDone,msg,setMsg}){const [style,setStyle]=useState('street'),[gender,setGender]=useState('neutral'),[busy,setBusy]=useState(false);async function create(){setBusy(true);const display=name||session.user.user_metadata?.display_name||'New Player';const p={id:session.user.id,display_name:display,gender,style,city:'Abuja',location_id:'home',x:20,y:78,money:25000,health:100,happiness:75,energy:90,reputation:0,xp:0};const {data,error}=await supabase.from('player_profiles').insert(p).select().single();if(error)setMsg(error.message);else onDone(data);setBusy(false)}return <main className="auth"><div className="auth-card character"><div className="eyebrow">CREATE YOUR CHARACTER</div><h1>Welcome to Abuja.</h1><input placeholder="Character name" value={name} onChange={e=>setName(e.target.value)}/><label>Style</label><div className="choices">{['street','classic','executive','sporty'].map(x=><button type="button" className={style===x?'choice active':'choice'} onClick={()=>setStyle(x)}>{x}</button>)}</div><label>Avatar</label><div className="choices">{['neutral','feminine','masculine'].map(x=><button type="button" className={gender===x?'choice active':'choice'} onClick={()=>setGender(x)}>{x}</button>)}</div><button className="primary" onClick={create} disabled={busy}>{busy?'Creating…':'Enter Abuja'}</button>{msg&&<div className="notice">{msg}</div>}</div></main>}

function Game({session,profile,setProfile}){
 const [selected,setSelected]=useState('home'),[travel,setTravel]=useState(false),[tab,setTab]=useState('map'),[online,setOnline]=useState(1),[remotePlayers,setRemotePlayers]=useState([]),[toast,setToast]=useState('');
 const place=places.find(p=>p.id===selected)||places[0],Icon=icons[place.type]||MapPin;
 useEffect(()=>{if(!supabase)return;const ch=supabase.channel('online-players',{config:{presence:{key:session.user.id}}}).on('presence',{event:'sync'},()=>{const state=ch.presenceState();const people=[];Object.entries(state).forEach(([key,entries])=>{const latest=entries?.[entries.length-1];if(latest&&key!==session.user.id)people.push(latest)});setRemotePlayers(people);setOnline(Object.keys(state).length)}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.track({user_id:session.user.id,name:profile.display_name,x:Number(profile.x),y:Number(profile.y)})});return()=>supabase.removeChannel(ch)},[session.user.id,profile.display_name,profile.x,profile.y]);
 function notify(x){setToast(x);setTimeout(()=>setToast(''),2500)}
 async function persist(next){const {error}=await supabase.from('player_profiles').update(next).eq('id',profile.id);if(error)notify(error.message);else setProfile(next)}
 async function move(){if(selected===profile.location_id){setTab('action');return}setTravel(true);setTimeout(async()=>{const delta=place.type==='club'?{energy:-15,happiness:10,reputation:2}:place.type==='work'?{energy:-20,money:5000,reputation:3}:place.type==='school'?{energy:-15,xp:15,reputation:2}:place.type==='home'?{energy:25,happiness:5}:{energy:-5,happiness:4};const next={...profile,location_id:place.id,x:place.x,y:place.y,energy:Math.max(0,Math.min(100,profile.energy+(delta.energy||0))),happiness:Math.max(0,Math.min(100,profile.happiness+(delta.happiness||0))),money:Math.max(0,profile.money+(delta.money||0)),reputation:profile.reputation+(delta.reputation||0),xp:profile.xp+(delta.xp||0)};await persist(next);setTravel(false);setTab('action')},550)}
 async function act(delta, message){await persist({...profile,...delta});notify(message)}
 async function buyPack(pack){setBusy(true);try{if(!supabase)throw new Error('Supabase is not configured.');const {data:{session:s}}=await supabase.auth.getSession();const {data,error}=await supabase.functions.invoke('paystack-create',{body:{pack_naira:pack.game}});if(error)throw error;if(data?.authorization_url)window.location.href=data.authorization_url;else throw new Error('Payment link was not returned.');}catch(e){notify(e.message||'Payment could not start.')}setBusy(false)}
 const [busy,setBusy]=useState(false);
 return <div className="game"><header><div className="brand"><img src="/logo.png"/><span>NIGERIA LIFESTYLE</span></div><div className="topstats"><span><Coins size={16}/>₦{profile.money.toLocaleString()}</span><span><Heart size={16}/>{profile.happiness}</span><span><Zap size={16}/>{profile.energy}</span><span><Users size={16}/>{online} online</span></div><button className="iconbtn" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/></button></header><div className="layout"><aside><div className="profile-card"><div className="avatar">{profile.display_name.slice(0,1).toUpperCase()}</div><div><strong>{profile.display_name}</strong><small>Level {Math.floor(profile.xp/100)+1} • {profile.style}</small></div></div><button className={tab==='map'?'nav active':'nav'} onClick={()=>setTab('map')}><Navigation/>Map</button><button className={tab==='action'?'nav active':'nav'} onClick={()=>setTab('action')}><Icon/>Selected place</button><button className={tab==='bank'?'nav active':'nav'} onClick={()=>setTab('bank')}><Wallet/>Bank / Top up</button><button className={tab==='business'?'nav active':'nav'} onClick={()=>setTab('business')}><Megaphone/>Advertise</button><button className="nav" onClick={()=>supabase.from('player_profiles').update(profile).eq('id',profile.id)}><Save/>Save game</button><div className="side-note"><Shield size={17}/><span>Reputation<br/><b>{profile.reputation}</b></span></div></aside>
 <section className="world">{tab==='map'||tab==='action'?<><div className="world-head"><div><div className="eyebrow">ABUJA • LIVE CITY</div><h2>Where do you want to go?</h2></div><div className="location-pill"><MapPin size={15}/>{places.find(p=>p.id===profile.location_id)?.name}</div></div><div className="map"><div className="roads"><i/><i/><i/><i/></div>{places.map(p=>{const I=icons[p.type]||MapPin;return <button key={p.id} className={'place '+p.type+(selected===p.id?' selected':'')} style={{left:p.x+'%',top:p.y+'%'}} onClick={()=>{setSelected(p.id);setTab('map')}}><span className="pin"><I size={17}/></span><b>{p.name}</b></button>})}{npcs.map(n=><div className="npc" style={{left:n[1]+'%',top:n[2]+'%'}} key={n[0]} title={n[0]}><span>{n[0][0]}</span></div>)}{remotePlayers.map((p,i)=><div key={p.user_id||i} className="remote-player" style={{left:Number(p.x)+'%',top:Number(p.y)+'%'}}><div className="remote-dot">{(p.name||'P')[0]}</div><span>{p.name||'Player'}</span></div>)}<div className="player" style={{left:profile.x+'%',top:profile.y+'%'}}><div className="player-dot">{profile.display_name[0]}</div><span>You</span></div>{travel&&<div className="travel">Travelling through Abuja…</div>}<div className="map-key"><span><i className="you"/>You</span><span><i className="people"/>Players</span><span><i className="spot"/>Places</span></div></div></>:tab==='bank'?<Bank profile={profile} buyPack={buyPack} busy={busy}/>:<Business profile={profile} notify={notify} />}</section>
 {tab==='map'||tab==='action'?<aside className="details"><div className="detail-top"><div className="place-icon"><Icon/></div><div><div className="eyebrow">{place.type.toUpperCase()}</div><h2>{place.name}</h2></div></div><p>{place.desc}</p><div className="action-list"><button onClick={move} disabled={travel}>{travel?'Travelling…':profile.location_id===place.id?'Enter / interact':'Move here'}<ChevronRight/></button>{place.type==='club'&&<button onClick={()=>act({happiness:Math.min(100,profile.happiness+8),energy:Math.max(0,profile.energy-10)},'You had a great night out.')}>Dance & socialize <Music/></button>}{place.type==='work'&&<button onClick={()=>act({money:profile.money+3000,xp:profile.xp+20,energy:Math.max(0,profile.energy-12)},'Shift complete: +₦3,000.')}>Work a shift <Coins/></button>}{place.type==='school'&&<button onClick={()=>act({xp:profile.xp+25,energy:Math.max(0,profile.energy-10)},'Class complete: +25 XP.')}>Attend class <GraduationCap/></button>}{place.type==='home'&&<button onClick={()=>act({energy:100,happiness:Math.min(100,profile.happiness+10)},'You rested and recovered.')}>Rest at home <House/></button>}{place.type==='shop'&&<button onClick={()=>act({money:Math.max(0,profile.money-2500),happiness:Math.min(100,profile.happiness+7)},'You bought a new lifestyle item for ₦2,500.')}>Buy lifestyle item · ₦2,500 <ShoppingBag/></button>}</div><div className="mini-stats"><Stat label="Health" value={profile.health}/><Stat label="Energy" value={profile.energy}/><Stat label="Happiness" value={profile.happiness}/></div><div className="tip"><Megaphone size={17}/><span>Earn Game Naira in the city, then spend it on things other players can see—including your own ad space.</span></div></aside>:<aside className="details"><div className="eyebrow">YOUR ECONOMY</div><h2>Build a life. Build a business.</h2><p>Players can top up Game Naira, earn it through play and spend it across the shared Abuja world.</p><div className="mini-stats"><div><small>Game Naira</small><b>₦{profile.money.toLocaleString()}</b></div><div><small>Level</small><b>{Math.floor(profile.xp/100)+1}</b></div></div></aside>}
 </div>{toast&&<div className="toast">{toast}</div>}</div>
}
function Bank({buyPack,busy,profile}){return <div className="panel"><div className="eyebrow">BANK APP</div><h2>Buy Game Naira</h2><p className="muted left">The game economy is fictional. Your real-money payment buys Game Naira at the displayed rate.</p><div className="balance-card"><Wallet/><div><small>Current Game Naira</small><strong>₦{profile.money.toLocaleString()}</strong></div></div><div className="pack-grid">{packs.map(p=><div className="pack" key={p.real}><div><small>REAL MONEY</small><strong>₦{p.real.toLocaleString()}</strong></div><ArrowUpRight/><div className="game-value">+₦{p.game.toLocaleString()} Game Naira</div><button className="primary" disabled={busy} onClick={()=>buyPack(p)}>{busy?'Opening checkout…':'Buy Game Naira'}</button></div>)}</div><div className="legal-note">Game Naira has no real-world cash value and cannot be withdrawn. Payments should be fulfilled only after verified payment confirmation.</div></div>}
function Business({profile,notify}){const [selected,setSelected]=useState(adSlots[0]),[business,setBusiness]=useState('My Business'),[link,setLink]=useState('https://'),[days,setDays]=useState(7);const total=selected.price*days/7;function reserve(){if(profile.money<total){notify('Not enough Game Naira. Earn more or top up.');return}notify('Demo reservation saved. Connect your real ad-payment flow before launch.')}return <div className="panel"><div className="eyebrow">BUSINESS DISTRICT</div><h2>Put your business on the city map</h2><p className="muted left">This turns the shared map into a marketplace. Players can see sponsored locations and tap them to discover a business.</p><div className="ad-grid">{adSlots.map(s=><button className={selected.id===s.id?'ad-card active':'ad-card'} onClick={()=>setSelected(s)} key={s.id}><Megaphone/><strong>{s.name}</strong><span>₦{s.price.toLocaleString()} / 7 days</span></button>)}</div><div className="form-card"><label>Business name<input value={business} onChange={e=>setBusiness(e.target.value)}/></label><label>Website / social link<input value={link} onChange={e=>setLink(e.target.value)}/></label><label>Days<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><div className="total"><span>Total Game Naira</span><strong>₦{total.toLocaleString()}</strong></div><button className="primary" onClick={reserve}>Reserve ad space</button></div></div>}
function Stat({label,value}){return <div><small>{label}</small><div className="bar"><i style={{width:value+'%'}}/></div><b>{value}</b></div>}
createRoot(document.getElementById('root')).render(<App/>);
